services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: symcomp_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devsermesmo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
