# Generated by Django 5.2.1 on 2025-06-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ocupacao', models.CharField(max_length=255)),
                ('biografia', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('link_apresentacao', models.URLField()),
                ('foto_url', models.URLField()),
                ('foto_alt', models.CharField(max_length=255)),
                ('links', models.ManyToManyField(related_name='palestrantes', to='api.link')),
            ],
        ),
    ]
