# Generated by Django 5.2.1 on 2025-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
