# Generated by Django 5.2.1 on 2025-06-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
